THIS MODEL CLASSIFIES THE GIVEN TEXT HAVING POSTIVE SENTIMENT OR NEGATIVE SENTIMENT

In [103]:
import pandas as pd 

In [104]:
train=pd.read_csv('labeledTrainData.tsv',header=0,delimiter='\t',quoting=3)

In [105]:
train.columns.values

array(['id', 'sentiment', 'review'], dtype=object)

In [106]:
train.head()

id  sentiment                                             review
0  "5814_8"          1  "With all this stuff going down at the moment ...
1  "2381_9"          1  "\"The Classic War of the Worlds\" by Timothy ...
2  "7759_3"          0  "The film starts with a manager (Nicholas Bell...
3  "3630_4"          0  "It must be assumed that those who praised thi...
4  "9495_8"          1  "Superbly trashy and wondrously unpretentious ...

In [107]:
train.shape

(25000, 3)

In [108]:
train.isnull().sum()
#There are no null values 

id           0
sentiment    0
review       0
dtype: int64

In [109]:
train.review[0]

'"With all this stuff going down at the moment with MJ i\'ve started listening to his music, watching the odd documentary here and there, watched The Wiz and watched Moonwalker again. Maybe i just want to get a certain insight into this guy who i thought was really cool in the eighties just to maybe make up my mind whether he is guilty or innocent. Moonwalker is part biography, part feature film which i remember going to see at the cinema when it was originally released. Some of it has subtle messages about MJ\'s feeling towards the press and also the obvious message of drugs are bad m\'kay.<br /><br />Visually impressive but of course this is all about Michael Jackson so unless you remotely like MJ in anyway then you are going to hate this and find it boring. Some may call MJ an egotist for consenting to the making of this movie BUT MJ and most of his fans would say that he made it for the fans which if true is really nice of him.<br /><br />The actual feature film bit when it finally

By Above we can observe that the text is having HTML tags, Stopwords, Special characters, before we going ahead we must pre-process all the text in the review column

WE SHALL REMOVE THE HTML TAGS FROM THE TEXT USING BEAUTIFUL SOUP 

In [110]:
from bs4 import BeautifulSoup

In [111]:
soup=BeautifulSoup(train.review[0])
Filt_text=soup.get_text()
print(Filt_text)

"With all this stuff going down at the moment with MJ i've started listening to his music, watching the odd documentary here and there, watched The Wiz and watched Moonwalker again. Maybe i just want to get a certain insight into this guy who i thought was really cool in the eighties just to maybe make up my mind whether he is guilty or innocent. Moonwalker is part biography, part feature film which i remember going to see at the cinema when it was originally released. Some of it has subtle messages about MJ's feeling towards the press and also the obvious message of drugs are bad m'kay.Visually impressive but of course this is all about Michael Jackson so unless you remotely like MJ in anyway then you are going to hate this and find it boring. Some may call MJ an egotist for consenting to the making of this movie BUT MJ and most of his fans would say that he made it for the fans which if true is really nice of him.The actual feature film bit when it finally starts is only on for 20 mi

REMOVING SPECIAL CHARACTER FROM THE TEXT USING REGEX

In [112]:
import re 
filt_text=re.sub('[^a-zA-Z]',' ',Filt_text)
print(filt_text)

 With all this stuff going down at the moment with MJ i ve started listening to his music  watching the odd documentary here and there  watched The Wiz and watched Moonwalker again  Maybe i just want to get a certain insight into this guy who i thought was really cool in the eighties just to maybe make up my mind whether he is guilty or innocent  Moonwalker is part biography  part feature film which i remember going to see at the cinema when it was originally released  Some of it has subtle messages about MJ s feeling towards the press and also the obvious message of drugs are bad m kay Visually impressive but of course this is all about Michael Jackson so unless you remotely like MJ in anyway then you are going to hate this and find it boring  Some may call MJ an egotist for consenting to the making of this movie BUT MJ and most of his fans would say that he made it for the fans which if true is really nice of him The actual feature film bit when it finally starts is only on for    mi

IT IS GOOD PRACTICE TO CONVERT ALL THE WORDS INTO LOWER CASE

In [113]:
filt_text.lower()

' with all this stuff going down at the moment with mj i ve started listening to his music  watching the odd documentary here and there  watched the wiz and watched moonwalker again  maybe i just want to get a certain insight into this guy who i thought was really cool in the eighties just to maybe make up my mind whether he is guilty or innocent  moonwalker is part biography  part feature film which i remember going to see at the cinema when it was originally released  some of it has subtle messages about mj s feeling towards the press and also the obvious message of drugs are bad m kay visually impressive but of course this is all about michael jackson so unless you remotely like mj in anyway then you are going to hate this and find it boring  some may call mj an egotist for consenting to the making of this movie but mj and most of his fans would say that he made it for the fans which if true is really nice of him the actual feature film bit when it finally starts is only on for    m

In [114]:
words=filt_text.split()

As a part of pre processing we should remove stop words from the given text

In [115]:
from nltk.corpus import stopwords
stopps=stopwords.words('english')
print(stopps)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [116]:
clean= [w for w in words if not  w in stopps]

print(clean)

#words = [w for w in words if not w in stopwords.words("english")]
#print (words)

['With', 'stuff', 'going', 'moment', 'MJ', 'started', 'listening', 'music', 'watching', 'odd', 'documentary', 'watched', 'The', 'Wiz', 'watched', 'Moonwalker', 'Maybe', 'want', 'get', 'certain', 'insight', 'guy', 'thought', 'really', 'cool', 'eighties', 'maybe', 'make', 'mind', 'whether', 'guilty', 'innocent', 'Moonwalker', 'part', 'biography', 'part', 'feature', 'film', 'remember', 'going', 'see', 'cinema', 'originally', 'released', 'Some', 'subtle', 'messages', 'MJ', 'feeling', 'towards', 'press', 'also', 'obvious', 'message', 'drugs', 'bad', 'kay', 'Visually', 'impressive', 'course', 'Michael', 'Jackson', 'unless', 'remotely', 'like', 'MJ', 'anyway', 'going', 'hate', 'find', 'boring', 'Some', 'may', 'call', 'MJ', 'egotist', 'consenting', 'making', 'movie', 'BUT', 'MJ', 'fans', 'would', 'say', 'made', 'fans', 'true', 'really', 'nice', 'The', 'actual', 'feature', 'film', 'bit', 'finally', 'starts', 'minutes', 'excluding', 'Smooth', 'Criminal', 'sequence', 'Joe', 'Pesci', 'convincing',

pre processing all the text in each record 

In [117]:
from bs4 import BeautifulSoup
import re 
from nltk.corpus import stopwords

In [118]:
def pre_processing(raw_text):
    soup=BeautifulSoup(raw_text,'html.parser')   #removing html tags if any 
    text1=soup.get_text()
    #removal of sepcial charcater if any 
    text2=re.sub('[^a-zA-Z]',' ',text1)
    #converting the above words into 
    text3=text2.lower().split()
    stops=set(stopwords.words('english'))
    clean_text=[w for w in text3 if not w in stops]
    return(" ".join(clean_text))
    

In [119]:
train.sentiment[0]

1

In [120]:
clean_text_records=list()
numbers=train['review'].size


for i in range(0,numbers):

    clean_text_records.append(pre_processing(train.review[i]))

clean_text_records[10000]

C:\Users\abhis\AppData\Local\Temp\ipykernel_22632\3524055099.py:2: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  soup=BeautifulSoup(raw_text,'html.parser')   #removing html tags if any


'would rated series perfect outstanding consistently high quality story character development last episode season final episode th season unending would certainly appear asgard killed rushed unconvincing unceremonious fashion left disbelief extremely rushed end series obvious many story arcs originally scheduled occur least one season guess would rapidly accelerated stories position stargate sg franchise two upcoming direct dvd moves unless asgard return future sg movie good explanation apparent extinction think fans cheated poor clean loose ends poor end otherwise brilliant sci fi series'

In [121]:
train.review[10000]

'"I would have rated the series a perfect 10 for outstanding and consistently high quality story and character development had it not been for the last episode of Season 10! <br /><br />The final episode of the 10th season \\"Unending\\", where (it would certainly appear that) the Asgard have been killed-off in a very rushed, unconvincing and very unceremonious fashion, left me in disbelief! <br /><br />From the extremely rushed end of the series, it\'s obvious that many of the story arcs were originally scheduled to occur over at least one more season. My guess would be that they rapidly accelerated these stories to position the Stargate SG-1 franchise for the two upcoming direct-to-DVD moves!<br /><br />Unless the Asgard return in a future SG-1 movie (with a very good explanation of the \\"apparent\\" extinction), I think that the fans have been cheated with a poor clean-up of loose-ends!<br /><br />Poor end to an otherwise brilliant sci-fi series."'

Now the text has been pre_processed

In [122]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer=CountVectorizer(max_features=1000)
vector=vectorizer.fit_transform(clean_text_records)
text_num=vector.toarray()
print(text_num)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


SO NOW WE HAVE CONVERTED TEXT INTO CORRESPONDING NUMERIC VALUE, WE WILL GIVING AS INPUT TO THE MACHINE LEARNING MODEL 

In [123]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
import numpy as np

forest=RandomForestClassifier(n_estimators=10,n_jobs=4)
forest.fit(text_num,train['sentiment'])
print (np.mean(cross_val_score(forest,text_num,train["sentiment"],cv=10)))

0.7691199999999999


RANDOM FOREST MODEL IS HAVING THE ACCURACY OF 77%

In [124]:
test=pd.read_csv('testData.tsv',header=0,delimiter='\t',quoting=3)

In [125]:
test.columns.values

array(['id', 'review'], dtype=object)

As this the test dataset having only two columns 

In [126]:
test_clean=list()
nums=test.review.size

for j in range(0,nums):

    test_clean.append(pre_processing(test.review[j]))

test_num=vectorizer.transform(test_clean)
clean_nums=test_num.toarray()
clean_nums

C:\Users\abhis\AppData\Local\Temp\ipykernel_22632\3524055099.py:2: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  soup=BeautifulSoup(raw_text,'html.parser')   #removing html tags if any


array([[0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

To predict the sentiment of the given text 

In [127]:
result=forest.predict(clean_nums)
result.shape

(25000,)

In [128]:
output=pd.DataFrame(data={'id':test['id'],'sentiment':result})

In [129]:
output.to_csv("bag_of_words", index=False, quoting=3)

In [139]:
piggy=[]
text_piggy=['she is very bad ']


#clean_text=pre_processing(text_piggy)
#clean_text

pigy_vector=vectorizer.transform(text_piggy)
pigy_num=pigy_vector.toarray()

piggy_op=forest.predict(pigy_num)
piggy_op
 

array([0], dtype=int64)